# Generated by Django 6.0.7 on 2026-07-25 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scan_receipts/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('raw_ocr_text', models.TextField(blank=True)),
                ('processed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateField()),
                ('weight_lb', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('skeletal_muscle_mass_lb', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('body_fat_mass_lb', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('total_body_water_lb', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('lean_body_mass_lb', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('percent_body_fat', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('basal_metabolic_rate_kcal', models.IntegerField(blank=True, null=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='scans.scanupload')),
            ],
        ),
    ]
