# Generated by Django 6.0.7 on 2026-08-09 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanresult',
            name='basal_metabolic_rate_kcal',
        ),
    ]
